{% set name = "atomistics" %}
{% set version = "0.2.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/atomistics-{{ version }}.tar.gz
  sha256: e200e0ba079bf8c5cb2b5ec80eeb8d37e4e50b159089579be402935cebd3e897

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - ase
    - numpy
    - scipy
    - spglib
    - versioneer
    - toml
    - setuptools
  run:
    - python >={{ python_min }},<3.13
    - ase >=3.23.0,<=3.24.0
    - numpy ==1.26.4
    - scipy >=1.11.1,<=1.15.2
    - spglib >=2.0.2,<=2.5.0

test:
  imports:
    - atomistics
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/pyiron/atomistics
  summary: atomistics - materials science workgflows to calculate material properties
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - pmrv
    - srmnitc
    - pyiron-runner
    - jan-janssen
