{% set name = "atomistics" %}
{% set version = "0.1.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/atomistics-{{ version }}.tar.gz
  sha256: 34b73a6758596ce9a54301860d78d3c8bbe4f320664279ae345d8035d649db6c

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
    - ase
    - numpy
    - scipy
    - spglib
    - versioneer
    - toml
  run:
    - python >=3.7
    - ase ==3.22.1
    - numpy >=1.23.5,<=1.26.2
    - scipy >=1.11.1,<=1.11.4
    - spglib >=2.0.2,<=2.1.0

test:
  imports:
    - atomistics
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/pyiron/atomistics
  summary: atomistics - materials science workgflows to calculate material properties
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - niklassiemer
    - pmrv
    - srmnitc
    - pyiron-runner
    - jan-janssen
