{% set name = "atomistics" %}
{% set version = "0.0.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/atomistics-{{ version }}.tar.gz
  sha256: fcc4b5623c6603e75180e6bb810beeb2477f247134602b4f9c3cea3320d2ff10

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - ase >=3.22.1
    - numpy >=1.23.5
    - scipy >=1.11.2
    - spglib >=2.0.2

test:
  imports:
    - atomistics
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/pyiron/atomistics
  summary: atomistics - materials science workgflows to calculate material properties
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - niklassiemer
    - pmrv
    - srmnitc
    - pyiron-runner
    - jan-janssen
