{% set name = "atomistics" %}
{% set version = "0.1.28" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/atomistics-{{ version }}.tar.gz
  sha256: ccee2445d05602f2d1104f4f8a664b89291fb8d1fa7598bfb9d389804123aaec

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.9,<3.13
    - pip
    - ase
    - numpy
    - scipy
    - spglib
    - versioneer
    - toml
  run:
    - python >=3.9,<3.13
    - ase ==3.22.1
    - numpy >=1.23.5,<=1.26.4
    - scipy >=1.11.1,<=1.13.1
    - spglib >=2.0.2,<=2.4.0

test:
  imports:
    - atomistics
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/pyiron/atomistics
  summary: atomistics - materials science workgflows to calculate material properties
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - pmrv
    - srmnitc
    - pyiron-runner
    - jan-janssen
