schema_version: 1

context:
  name: atomistics
  version: "0.3.6"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/atomistics-${{ version }}.tar.gz
  sha256: a4804bbbb43aa41c7dc80538abd98754f2b7558f6f2cd1b625b8620eaed4fbf1

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - ase
    - numpy
    - scipy
    - spglib
    - hatchling
    - hatch-vcs
  run:
    - python >=${{ python_min }}
    - ase >=3.23.0,<=3.28.0
    - numpy >=1.26.4,<=2.4.3
    - scipy >=1.11.1,<=1.17.1
    - spglib >=2.0.2,<=2.7.0

tests:
  - python:
      imports:
        - atomistics
      python_version: ${{ python_min }}.*
  - requirements:
      run:
        - pip
        - python ${{ python_min }}.*
    script:
      - pip check

about:
  summary: atomistics - materials science workgflows to calculate material properties
  license: BSD-3-Clause
  license_file: LICENSE
  homepage: https://github.com/pyiron/atomistics

extra:
  recipe-maintainers:
    - pyiron-runner
    - jan-janssen
