schema_version: 1

context:
  name: atomistics
  version: "0.3.0"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/atomistics-${{ version }}.tar.gz
  sha256: 088290618756440eb9d8babace34680b118ddf2457639d98557ea0aa1433c4f9
  patches:
    - scipy.patch

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - ase
    - numpy
    - scipy
    - spglib
    - versioneer
    - toml
    - setuptools
  run:
    - python >=${{ python_min }},<3.13
    - ase >=3.23.0,<=3.25.0
    - numpy ==1.26.4
    - scipy >=1.11.1,<=1.15.2
    - spglib >=2.0.2,<=2.6.0

tests:
  - python:
      imports:
        - atomistics
      python_version: ${{ python_min }}.*
  - requirements:
      run:
        - pip
        - python ${{ python_min }}.*
    script:
      - pip check

about:
  summary: atomistics - materials science workgflows to calculate material properties
  license: BSD-3-Clause
  license_file: LICENSE
  homepage: https://github.com/pyiron/atomistics

extra:
  recipe-maintainers:
    - pmrv
    - srmnitc
    - pyiron-runner
    - jan-janssen
