schema_version: 1

context:
  name: atomistics
  version: "0.3.10"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/atomistics-${{ version }}.tar.gz
  sha256: 61556418fd629f20c23c09b548b6bea3accec82eb9f517e6834f59cfcd4fe9b1

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - ase
    - numpy
    - scipy
    - spglib
    - hatchling
    - hatch-vcs
  run:
    - python >=${{ python_min }}
    - ase >=3.23.0,<=3.29.0
    - numpy >=1.26.4,<=2.5.3
    - scipy >=1.11.1,<=1.18.1
    - spglib >=2.0.2,<=2.7.0

tests:
  - python:
      imports:
        - atomistics
      pip_check: true
      python_version:
        - ${{ python_min }}
        - "*"

about:
  summary: atomistics - materials science workgflows to calculate material properties
  license: BSD-3-Clause
  license_file: LICENSE
  homepage: https://github.com/pyiron/atomistics

extra:
  recipe-maintainers:
    - pyiron-runner
    - jan-janssen
